### ISSUE TITLE
Parsing channels... /usr/local/bin/iptv: line 33: readarray: command not found

### ISSUE THREAD

**Issue by m0llysour** [shahin8r/iptv#1]
When running `iptv https://iptv-org.github.io/iptv/languages/jpn.m3u`

I get
```
Loading channels... Done!
Parsing channels... /usr/local/bin/iptv: line 33: readarray: command not found
Done!
Playlist saved. Now run iptv again without a M3U URL.
````

Then no playlist is loaded. I'm on Macos 10.15.7.
Lovely work, thanks!

**Comment by shahin8r** [comment]
Thanks for submitting the issue @m0llysour. This has now been fixed and merged. Let me know if it works for you. :)
