### ISSUE TITLE
invalid grep option

### ISSUE THREAD

**Issue by DLewis01** [shahin8r/iptv#6]
After selecting a channel I get the following. Seems my version of Grep does not support the -P option.

iptv
grep: invalid option -- P
usage: grep [-abcdDEFGHhIiJLlMmnOopqRSsUVvwXxZz] [-A num] [-B num] [-C[num]]
	[-e pattern] [-f file] [--binary-files=value] [--color=when]
	[--context[=num]] [--directories=action] [--label] [--line-buffered]
	[--null] [pattern] [file ...]

**Comment by DLewis01** [comment]
quick fix, replace line 81 with

selected_channel_url=$(echo "$selected_channel_line" | perl -nle'print $& while m{url:\K.*}g'| tr -d '\r')

**Comment by shahin8r** [comment]
Please let me know if it works as expected now.

**Comment by JamesRivers** [comment]
or use ggrep - brew install grep - replace grep with ggrep in the script

**Comment by DLewis01** [comment]
> Please let me know if it works as expected now.

works great now.
